{{- if .Values.service.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-wireguard"
  labels:
    {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    app: "{{ .Release.Name }}-wireguard"
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: wg
    protocol: UDP
    port: {{ .Values.service.port }}
    targetPort: 51820
    {{- if .Values.service.type | eq "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: "{{ .Release.Name }}-wireguard"
{{- end }}